deployment:
  tasks:
    - echo "Starting deployment..."
    - export DEPLOY_PATH=/home/sintraci/repositories/sintracv2
    - /bin/cp -R $DEPLOY_PATH/public/* /home/sintraci/public_html
    - cd $DEPLOY_PATH
    - /bin/cp .env.example .env
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader
    - php artisan key:generate
    - php artisan config:clear
    - php artisan cache:clear
    - php artisan config:cache
    - php artisan route:cache
    - php artisan migrate --force
    - echo "Deployment finished."
